IF
	Allegiance(Myself,NEUTRAL)
	OR(3)
	Allegiance("CPMELVIN",ENEMY)
	Allegiance("CPCLRK01",ENEMY)
	Allegiance("CPFIGH01",ENEMY)
THEN
	RESPONSE #100
		Enemy()
		Attack(NearestEnemyOf(Myself))
END

IF
  Global("CPMelvinHQArrival","GLOBAL",1)
  Global("CPMelvinHQArrivalD","GLOBAL",0)
THEN
  RESPONSE #100
  SetGlobal("CPMelvinHQArrivalD","GLOBAL",1)
  StartDialogNoSet([PC])
END

IF
  Die()
  Global("CPMelvinHQArrival","GLOBAL",0)
THEN
  RESPONSE #100
  SetGlobal("CPMelvinDead","GLOBAL",1)
END